name: Build And Publish

# on:
#   push:
#     branches:
#       - main
on: [pull_request]

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, tag, and push image to GHCR
        env:
          IMAGE_TAG: ${{ github.sha }}
          BRANCH: ${{ github.ref }}
        run: |
          APP_RELEASE=$(date +"1.%y%m%d.%H%M%S" | sed -E 's/\.0{1,3}/./g')

          docker build --cache-from $REGISTRY/ahmad-rw/stg-ctb:latest -t $REGISTRY/ahmad-rw/stg-ctb:$APP_RELEASE -t $REGISTRY/ahmad-rw/stg-ctb:$IMAGE_TAG -t $REGISTRY/ahmad-rw/stg-ctb:latest -f docker/Dockerfile .
          docker push $REGISTRY/ahmad-rw/stg-ctb:$IMAGE_TAG
          docker push $REGISTRY/ahmad-rw/stg-ctb:latest
          docker push $REGISTRY/ahmad-rw/stg-ctb:$APP_RELEASE